#!/bin/bash

# ДИАГНОСТИЧЕСКИЙ СКРИПТ ДЛЯ ПРОВЕРКИ МОДЕЛЕЙ
# Проверяет реальные ответы API

echo "════════════════════════════════════════════════════════════════════════════════"
echo "           ДИАГНОСТИКА: ИСТОЧНИКИ СПИСКОВ МОДЕЛЕЙ"
echo "════════════════════════════════════════════════════════════════════════════════"

echo ""
echo "1️⃣  ПРОВЕРКА GET /api/models/all (все модели для админки)"
echo "─────────────────────────────────────────────────────────────────────────────────"
echo "curl -s http://localhost:3080/api/models/all | jq '.' | head -50"
echo ""
curl -s http://localhost:3080/api/models/all | jq '.' | head -50 2>&1 || echo "❌ Ошибка подключения или API недоступен"

echo ""
echo ""
echo "2️⃣  ПРОВЕРКА GET /api/models/allowed (разрешенные модели для пользователя)"
echo "─────────────────────────────────────────────────────────────────────────────────"
echo "📝 Требует аутентификации!"
echo "Для тестирования используйте токен из браузера:"
echo ""
echo "curl -s -H 'Authorization: Bearer <YOUR_TOKEN>' http://localhost:3080/api/models/allowed | jq '.'"
echo ""
echo "(Или просто откройте DevTools → Network → найдите запрос /api/models/allowed)"

echo ""
echo ""
echo "3️⃣  ПРОВЕРКА GET /api/config (стартовая конфигурация)"
echo "─────────────────────────────────────────────────────────────────────────────────"
echo "curl -s http://localhost:3080/api/config | jq '.modelSpecs' | head -30"
echo ""
curl -s http://localhost:3080/api/config 2>/dev/null | jq '.modelSpecs' 2>/dev/null | head -30 || echo "❌ Ошибка подключения или API недоступен"

echo ""
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo "ИНСТРУКЦИИ ДЛЯ ПРОВЕРКИ В БРАУЗЕРЕ:"
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "1. Откройте браузер: http://localhost:3080"
echo "2. Откройте DevTools (F12)"
echo "3. Перейдите на вкладку Network"
echo "4. Откройте селектор моделей в чате"
echo "5. Ищите эти запросы:"
echo "   ✅ GET /api/models/allowed (должен быть запрос)"
echo "   ❓ Есть ли он?"
echo ""
echo "6. Смотрите на вкладке Console (F12 → Console):"
echo "   ✅ Должны видны логи [MODELS_DIAGNOSTIC]"
echo "   ❓ Какие логи видны?"
echo ""
echo "7. В ответе /api/models/allowed проверьте:"
echo "   - models: [список моделей]"
echo "   - plan: [текущий план пользователя]"
echo ""

